### ISSUE TITLE
Wrong variable in a_filter

### ISSUE THREAD

**Issue by addap** [Denommus/monadic#1]
Hi, 
first of all thanks for the great monad library! I used it in a project and it was way more pleasant to compose monads than with the existing library of the BAP project.

I noticed a typo in the definition of a_filter, it should be `C.cons curr ys` instead since xs is the original list.
https://github.com/Denommus/monadic/blob/697fa651b49d51b018bb598fc0c0810754bdb1e5/library/monad.ml#L317

**Comment by Denommus** [comment]
@addap hey, addap, sorry for the extreme delay, but I pushed an update for that on master.
